version: '3.5'
services:
  db:
    image: mysql:8.0
    restart: always
    network_mode: bridge
    environment:
      - MYSQL_USER=delivery
      - MYSQL_PASSWORD=delivery
      - MYSQL_DATABASE=delivery
      - MYSQL_ROOT_PASSWORD=delivery
    ports:
      - '3306:3306'